spring:
  freemarker:
    template-loader-path: classpath:/template
    suffix: .ftl
# 日志
logging:
  file: mytool.log
  level:
    org.fcx.mytool: info
mytool:
  proxy-links-file-path: file:proxy_links.json