# 服务器配置
server:
  port: 80
# 数据库驱动配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytool?serverTimezone=Asia/Shanghai
    username: hecate
    password: fcx9mysql
logging:
  level:
    org.fcx.mytool: info