spring:
  freemarker:
    template-loader-path: classpath:/template
    suffix: .ftl
  profiles:
    active: dev
# 日志
logging:
  file: mytool.log
  level:
    org.fcx.mytool: info
mytool:
  proxy-links-file-path: file:proxy_links.json
  proxy-host: 127.0.0.1
  proxy-port: 7890
  use-proxy: true
